/* Copyright 2019 DevFactory FZ LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import net "net"

import time "time"

// ConntrackHelper is an autogenerated mock type for the ConntrackHelper type
type ConntrackHelper struct {
	mock.Mock
}

// RemoveEntriesDNATingToIP provides a mock function with given fields: ip
func (_m *ConntrackHelper) RemoveEntriesDNATingToIP(ip net.IP) (time.Duration, error) {
	ret := _m.Called(ip)

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(net.IP) time.Duration); ok {
		r0 = rf(ip)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(net.IP) error); ok {
		r1 = rf(ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
